### ISSUE TITLE
Issue using formatter in patient detail page

### ISSUE THREAD

**Issue by bruth** [chop-dbhi/harvest-openmrs#70]
```pytb
Traceback (most recent call last):

 File "/home/devuser/webapps/harvest-openmrs-env/lib/python2.7/site-packages/django/core/handlers/base.py", line 113, in get_response
   response = callback(request, *callback_args, **callback_kwargs)

 File "openmrs/views.py", line 75, in patient_view
   table, = format_concept(dc, [r.cd4, r.cd4_percent, r.cd8, r.sgpt, r.sgpt, r.alc], formats=['html'])

 File "openmrs/views.py", line 11, in format_concept
   return f(values)

 File "/home/devuser/webapps/harvest-openmrs-env/src/avocado/avocado/formatters.py", line 158, in __call__
   record = self._recordclass(*values)

TypeError: __new__() takes exactly 6 arguments (7 given)
```

**Comment by bruth** [comment]
Fixed in 72cd00f78ae92ef81bbee65e1ebb7cc7e5c86ee5
